In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import seaborn as sns



In [3]:
# loading data
data = load_iris()

In [4]:
X=data.data
X.shape


(150, 4)

In [5]:
y=data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [7]:
scaler=StandardScaler()

In [8]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
model=Sequential()
model.add(Dense(64,input_shape=(X_train.shape[1],),activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])


In [9]:
model.fit(X_train,y_train,epochs=100,batch_size=32,validation_split=0.2)

Epoch 1/100
3/3 [==============================] - 1s 102ms/step - loss: 1.1231 - accuracy: 0.1771 - val_loss: 1.0561 - val_accuracy: 0.4583
Epoch 2/100
3/3 [==============================] - 0s 16ms/step - loss: 1.0576 - accuracy: 0.3229 - val_loss: 1.0036 - val_accuracy: 0.7083
Epoch 3/100
3/3 [==============================] - 0s 16ms/step - loss: 0.9958 - accuracy: 0.5938 - val_loss: 0.9550 - val_accuracy: 0.8750
Epoch 4/100
3/3 [==============================] - 0s 16ms/step - loss: 0.9396 - accuracy: 0.7500 - val_loss: 0.9080 - val_accuracy: 0.9167
Epoch 5/100
3/3 [==============================] - 0s 16ms/step - loss: 0.8868 - accuracy: 0.7812 - val_loss: 0.8631 - val_accuracy: 0.8750
Epoch 6/100
3/3 [==============================] - 0s 11ms/step - loss: 0.8373 - accuracy: 0.8021 - val_loss: 0.8215 - val_accuracy: 0.8750
Epoch 7/100
3/3 [==============================] - 0s 16ms/step - loss: 0.7904 - accuracy: 0.8021 - val_loss: 0.7824 - val_accuracy: 0.8750
Epoch 8/100
3/3 [==

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                320       
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
Total params: 2,499
Trainable params: 2,499
Non-trainable params: 0
_________________________________________________________________


In [16]:
feature_extractor=Sequential(model.layers[:-1])
train_feature=feature_extractor.predict(X_train)


4/4 [==============================] - 0s 0s/step
(120, 32)


In [25]:
test_feature=feature_extractor.predict(X_test)

1/1 [==============================] - 0s 32ms/step


In [26]:
test_feature

array([[7.37693071e-01, 8.37623596e-01, 0.00000000e+00, 2.27958113e-02,
        6.22422040e-01, 0.00000000e+00, 0.00000000e+00, 8.05046678e-01,
        1.07653546e+00, 8.79406512e-01, 9.84711766e-01, 0.00000000e+00,
        0.00000000e+00, 2.50891089e-01, 6.05898201e-01, 1.86895683e-01,
        8.89547288e-01, 0.00000000e+00, 2.85571992e-01, 0.00000000e+00,
        5.79223394e-01, 0.00000000e+00, 5.17117798e-01, 0.00000000e+00,
        9.56920266e-01, 0.00000000e+00, 1.05142760e+00, 0.00000000e+00,
        4.35933441e-01, 3.86348218e-01, 4.94610250e-01, 0.00000000e+00],
       [2.44656131e-01, 3.06643903e-01, 1.68724251e+00, 1.18244660e+00,
        0.00000000e+00, 8.79019678e-01, 0.00000000e+00, 6.32089376e-02,
        0.00000000e+00, 5.64780951e-01, 0.00000000e+00, 1.59956098e+00,
        0.00000000e+00, 7.78869689e-02, 2.28382540e+00, 4.50405777e-02,
        3.44555557e-01, 0.00000000e+00, 1.40018797e+00, 1.94545591e+00,
        2.11379766e+00, 0.00000000e+00, 0.00000000e+00, 1.42539

In [27]:
train_feature

array([[0.0000000e+00, 4.4336438e-01, 2.1892560e+00, ..., 1.4367390e-01,
        0.0000000e+00, 1.3723382e+00],
       [7.0353515e-02, 0.0000000e+00, 2.1283619e+00, ..., 0.0000000e+00,
        0.0000000e+00, 5.9164697e-01],
       [9.7844446e-01, 9.9722016e-01, 2.4101920e-02, ..., 3.7455139e-01,
        4.9811876e-01, 1.7993711e-03],
       ...,
       [2.1372047e-01, 2.0395526e-01, 1.9725084e+00, ..., 0.0000000e+00,
        0.0000000e+00, 5.5662233e-01],
       [6.8533850e-01, 1.2032689e+00, 0.0000000e+00, ..., 4.0834728e-01,
        2.3732400e-01, 5.0828647e-02],
       [5.1421952e-01, 1.6115002e-01, 6.0870081e-01, ..., 0.0000000e+00,
        1.8823090e+00, 1.1662263e+00]], dtype=float32)

In [28]:
#normalize
scaler=StandardScaler()

In [43]:
X_TR=scaler.fit_transform(train_feature)
X_TT=scaler.transform(test_feature)

In [44]:
from sklearn.svm import SVC

In [45]:
svm_m=SVC(kernel='linear')

In [46]:
svm_m.fit(X_TR,y_train)

SVC(kernel='linear')

In [47]:
predicted=svm_m.predict(X_TT)

In [48]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [49]:
accuracy_score(y_test,predicted)

1.0

In [50]:
confusion_matrix(y_test,predicted)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)